{% set name = "cgen" %}
{% set version = "2019.1" %}
{% set sha256 = "d5285fe4e6202aed7c7f16fb6606b885c34c30e93a3ca6c7d33839e1a5fbfd11" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
    build:
        - python
        - setuptools
        - pytools
        - six
        - pip
    run:
        - python
        - pytools
        - numpy
        - six

test:
    requires:
        - pytest
    imports:
        - {{ name }}
    source_files:
        - test
    commands:
         - cd test && python -m pytest

about:
    home: http://pypi.python.org/pypi/cgen
    license: MIT
    license_file: LICENSE
    summary: C/C++ source generation from an AST
    doc_url: https://documen.tician.de/cgen
    dev_url: http://github.com/inducer/cgen

extra:
    recipe-maintainers:
        - inducer
