{% set name = "cgen" %}
{% set version = "2017.1" %}
{% set sha256 = "a04525d51ee975d37d590d6d82bf80a46e77f75187cccfd2248a89616a778795" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    noarch: python
    number: 1
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - setuptools
        - pytools
        - six
        - pip
    run:
        - python
        - pytools
        - numpy
        - six

test:
    requires:
        - pytest
    imports:
        - {{ name }}
    source_files:
        - test
    commands:
         - cd test && python -m pytest

about:
    home: http://pypi.python.org/pypi/cgen
    license: MIT
    license_file: LICENSE
    summary: C/C++ source generation from an AST
    doc_url: https://documen.tician.de/cgen
    dev_url: http://github.com/inducer/cgen

extra:
    recipe-maintainers:
        - inducer
