{% set name = "cgen" %}
{% set version = "2020.1" %}
{% set sha256 = "4ec99d0c832d9f95f5e51dd18a629ad50df0b5464ce557ef42c6e0cd9478bfcf" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    noarch: python
    number: 1
    script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
    build:
        - python >=3.8
        - setuptools
        - pytools
        - six
        - pip
    run:
        - python >=3.8
        - pytools
        - numpy
        - six

test:
    requires:
        - pytest
    imports:
        - {{ name }}
    source_files:
        - test
    commands:
         - cd test && python -m pytest

about:
    home: http://pypi.python.org/pypi/cgen
    license: MIT
    license_file: LICENSE
    summary: C/C++ source generation from an AST
    doc_url: https://documen.tician.de/cgen
    dev_url: http://github.com/inducer/cgen

extra:
    recipe-maintainers:
        - inducer
