# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "G1wk9aoSChnGhdHfaDCXSZYfgrfpTb6BezRgOu0KA5tx1pyNXPgyNNcfPZ4b+zSHftu1hoZsxQgO77jII6Yj2GQ9Cj92JyEyTrsP2EQaDSeGjQtuPkX0dgodxtldwIfV0gzIz7iTMnNG5c4i4UdDD57Y5evOI54AAOco9fL0mtax6rQ8v2esMwWGWil9fYsdIrxjjb+xLF1mLOTzWoxmWzvVeZIAkgdxmCxOjwgT4c9q4mf9dYGpMVionkXRhNd3DTlmHR//Jb0FXHos7QEo76f9pYKW6C3dE5ZR7u1v9OZeTbhf1kYPFs9NJ6TebxjlslXBjxwfTxOfiNc5gPAVZaUyWvmV5MZhtUp7Uewm9+2ztKcUYKKgpMr2FF3fYLcrlhIAG+QLYC/6AwqDRAOnhw4AV5omRJ/sji6oI61jT8WfPb6S7f8IbzvBd032syg6THJNvrWblfq0PZDaQ7UPxKi4V8IZpN8sAUMhPxm/y0fXB3LFTBBFMzlPPKMiVDUc20Zz7xrDFJ0t+pK3/oamkzm6AYT7bTawLUkBFc95AVsiQNjCdd4AygxFHt8cRTOYQ2IMTRqFFaD4EDabwy5Zcz0wT5nuiiFQ7NvAJTnBcUZ5MQQwMkXpl9AHqOAPn5H/YRU7UvQBeAhlkai9BCZYe6xReS/mUPzPPLKk+0Gdkmg="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
