travis:
  secure:
    BINSTAR_TOKEN: 2gBR+Y0PDsxAuY6jRaTKNUM9661Tr5J3tl/PEPJhWsmbcoWMICgWybzJI5YrKZP8yrgy+eqJpJ9vtpw86USz9/Al3JZHmLd0FilhvYW03c1VXgSc3klKRHOSd2SrbVT7uvRK++fo7Zx6JPAQW6zfyw90UcxgGsq0JtVuF+udJQl2Izb6R6W6pVmYAEbkl9BBpNhdwRbjYuKzUwi/Bmynx+jiHzuWrf+PDa2Klc800oJWzxLguR37jmLt0agKFBo5kuNz+0jnUsGVoVrObgw2nxrq0ZMFae7/VGHFLwooHxAL1Lim8ER80ijPJFir23zHHNoZiNEFaZqfSW4nZ9Y3rMEuiAeNn8rmuSFdx7sIWftf2AWQerXeWhNlSUhuYssD9DVKM2uEjZh4vmVKDHs1PyZGTKJBlUTBaGCO3FiCz9D3b18GyMGJHDqWpKIQVeoYEl9oysfET9an+yNcKVz95MYp/UzfMctRB8I2S5Rvs119MpirO89rSk1AODuRnpbJrDP+tw76FA41yVA9aLgw1oDyWqD78oeXxqjvg2dcSPSnIw5weUi1ZAV2hTjkA3fpGry0ympVup7WJ99FhJYQTOqPWkK0xrK0HjQHWJFMvDiVuOw93VTqrGRr0rrtwSlvoesazKja9uc0KBiqp57Vzb+AhNNy9mk7R6jG6dB31Dg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
