travis:
  secure:
    BINSTAR_TOKEN: JTiVI5Xfjz+Um6hDmB9bxfxzmT3Iqf8QoaOUEa8yl9inwkFDSIR9oM5mZoZIBPEcsT5YuBOeM3Lte37eMApipyuEAjBALMOILQyGE7hIx3s3cMvPYO2NMwn5tt6n5w2o/dRYM62PTxuVp+EanxhK2kz5aX3wiNc0CMhoXTeyulowv3eVUuPRzvlsGl4TxDjWQhtshdLDOmJNhrJr2Fibkh5GE2u5fj2aXXBlJiTtWZ2WNbpQs2UWl58qqHhLAc71KK+TSJRPLUxuJsOIo2cvLzh5GymHOwhDCSgNOq/VqTN2yO900JoASB4apjVM6KdIbbKyBnKYor1EUQpPIhJ+UQC1e900vGT2uL/QGSJBF1oEfF/47KQPcHDWb1eAoLV5cBsjoJ5WnZ2/TeozITJgnC7bVp47p68R3OWCqX1SF/DJuFRa5Sd1KYfM4WY9I/9RFTk0wlaXo5HYq5/yJ7M/ZLpnrGN+6h1MOJ03QCxiD9VtZ9FVL+5PUArJqyFS15OofU0vEPpBA4X8WvPDur6IuHKSn6YZpG47zM5cCKlwVdMB5uVE9hPmE7QeKLbGbmLgSz99e0mo6mLgBUqmj+vwx+o6StMNe6eyzLo/34ZC2s3LsbpbWY3MggQCl45MfNJyI2rNaxAYCcc6BwQeKp9Zhs/ntMjNzdl2E69exy98T4Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
